{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hostswitch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HostSwitch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HostSwitch/HostSwitch_{{ version }}.tar.gz
  sha256: 26609eee4117ab65d47aeb688a4a738b3423524bfc5645a81e23d27286b1b43f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-ggplot2
    - r-plyr
    - r-purrr
    - r-shiny
    - r-tippy
  run:
    - r-base
    - r-checkmate
    - r-ggplot2
    - r-plyr
    - r-purrr
    - r-shiny
    - r-tippy

test:
  commands:
    - $R -e "library('HostSwitch')"           # [not win]
    - "\"%R%\" -e \"library('HostSwitch')\""  # [win]

about:
  home: https://github.com/berndpanassiti/HostSwitch
  license: GPL-3.0-or-later
  summary: Using a simulation-based approach, the 'HostSwitch' package provides functions to investigate host switches by consumers. The individual-based model is based on the concept of ecological fitting. The mockup model is published by Araujo et al. 2015. Understanding Host-Switching by Ecological Fitting (<doi:10.1371/journal.pone.0139225>).
    The package provides an R-friendly and modified version of this model which can be applied to different consumer-resource scenarios.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
